### ISSUE TITLE
Install instructions needed

### ISSUE THREAD

**Issue by paulvanbladel** [imjustd/flexbox-playground#1]
Needs compass and Ruby, can you please describe (or link) how to install. thx.

**Comment by bitconym** [comment]
I will update the Readme with install instructions later this week. Stay tuned.

**Comment by bitconym** [comment]
Added install instructions in the README file (Fix e27caad5aeda1e3bc04132a500a196e73ee149c8)

**Comment by paulvanbladel** [comment]
Thanks.
